language: node_js
node_js:
  - "node"
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
  - CI='' npm run build
before_script:
  - npm start -- --silent &
script:
  - $(npm bin)/cypress run
deploy:
  provider: vercel
  app: backcountry-buddy-ui
  skip_cleanup: true