language: node_js
node_js:
  - "node"
notifications:
  email: false
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm i
  - npm ci
  - npm update
  - npm run build
before_script:
  - npm start -- --silent &
script:
  - $(npm bin)/cypress run
